// Copyright 2025 Morgan Newell Sun
// SPDX-License-Identifier: GPL-2.0-or-later

#ifdef RGBLIGHT_ANIMATIONS
#    undef RGBLIGHT_ANIMATIONS
#endif
#ifdef RGBLIGHT_EFFECT_ALTERNATING
#    undef RGBLIGHT_EFFECT_ALTERNATING
#endif
#ifdef RGBLIGHT_EFFECT_BREATHING
#    undef RGBLIGHT_EFFECT_BREATHING
#endif
#ifdef RGBLIGHT_EFFECT_CHRISTMAS
#    undef RGBLIGHT_EFFECT_CHRISTMAS
#endif
#ifdef RGBLIGHT_EFFECT_KNIGHT
#    undef RGBLIGHT_EFFECT_KNIGHT
#endif
#ifdef RGBLIGHT_EFFECT_RAINBOW_MOOD
#    undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#endif
#ifdef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#    undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#endif
#ifdef RGBLIGHT_EFFECT_RGB_TEST
#    undef RGBLIGHT_EFFECT_RGB_TEST
#endif
#ifdef RGBLIGHT_EFFECT_SNAKE
#    undef RGBLIGHT_EFFECT_SNAKE
#endif
#ifdef RGBLIGHT_EFFECT_STATIC_GRADIENT
#    undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#endif
#ifdef RGBLIGHT_EFFECT_TWINKL
#    undef RGBLIGHT_EFFECT_TWINKL
#endif